//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_GrabPullLocomotion : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean GrabR
        {
            get
            {
                return SteamVR_Actions.grabPullLocomotion_GrabR;
            }
        }
        
        public virtual SteamVR_Action_Single Pull
        {
            get
            {
                return SteamVR_Actions.grabPullLocomotion_Pull;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabL
        {
            get
            {
                return SteamVR_Actions.grabPullLocomotion_GrabL;
            }
        }
        
        public virtual SteamVR_Action_Boolean BuildMenu
        {
            get
            {
                return SteamVR_Actions.grabPullLocomotion_BuildMenu;
            }
        }
        
        public virtual SteamVR_Action_Boolean GripR
        {
            get
            {
                return SteamVR_Actions.grabPullLocomotion_GripR;
            }
        }
        
        public virtual SteamVR_Action_Boolean GripL
        {
            get
            {
                return SteamVR_Actions.grabPullLocomotion_GripL;
            }
        }
        
        public virtual SteamVR_Action_Boolean East
        {
            get
            {
                return SteamVR_Actions.grabPullLocomotion_East;
            }
        }
        
        public virtual SteamVR_Action_Boolean West
        {
            get
            {
                return SteamVR_Actions.grabPullLocomotion_West;
            }
        }
        
        public virtual SteamVR_Action_Boolean MainMenu
        {
            get
            {
                return SteamVR_Actions.grabPullLocomotion_MainMenu;
            }
        }
    }
}
